# Generated by Django 5.0.1 on 2024-01-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
